openapi: 3.0.0
info:
  title: Coments
  version: 1.0.0
  description: Comments enpoints

paths:
  /api/comment/post:
    post:
      summary: Criar um comentário
      tags:
        - Comments
      description: Permite que um usuário crie um comentário em um post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: string
                  example: "64f1b2b3c7e9b4f8f8f8f8f8"
                postID:
                  type: string
                  example: "64f1b2b3c7e9b4f8f8f8f8f9"
                content:
                  type: string
                  example: "Este post é incrível!"
      responses:
        '201':
          description: Comentário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "comentario adicionado"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "64f1b2b3c7e9b4f8f8f8f8f9"
                      title:
                        type: string
                        example: "Meu primeiro post"
        '404':
          description: Usuário ou post não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuario ou post não encontrado!"
        '500':
          description: Erro ao criar comentário
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "erro ao adicionar comentario"
                  error:
                    type: string
                    example: "Erro interno do servidor"

  /api/comment/post/{postID}:
    get:
      summary: Listar comentários de um post
      tags:
        - Comments
      description: Retorna todos os comentários de um post específico.
      parameters:
        - name: postID
          in: path
          required: true
          description: ID do post
          schema:
            type: string
            example: "64f1b2b3c7e9b4f8f8f8f8f9"
      responses:
        '200':
          description: Comentários listados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "comentarios encontradas com sucesso."
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "64f1b2b3c7e9b4f8f8f8f8f9"
                        author:
                          type: object
                          properties:
                            name:
                              type: string
                              example: "João Silva"
                            username:
                              type: string
                              example: "joaosilva"
                            avatar:
                              type: string
                              example: "https://example.com/profile.jpg"
                        content:
                          type: string
                          example: "Este post é incrível!"
                        createdAt:
                          type: string
                          format: date-time
                          example: "2023-09-01T12:00:00Z"
                        updatedAt:
                          type: string
                          format: date-time
                          example: "2023-09-01T12:00:00Z"
        '500':
          description: Erro ao listar comentários
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "erro ao listar comentarios"
                  error:
                    type: string
                    example: "Erro interno do servidor"

  /api/comment/{commentID}:
    delete:
      summary: Deletar um comentário
      tags:
        - Comments
      description: Permite que um usuário delete um comentário.
      parameters:
        - name: commentID
          in: path
          required: true
          description: ID do comentário
          schema:
            type: string
            example: "64f1b2b3c7e9b4f8f8f8f8f9"
      responses:
        '200':
          description: Comentário deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comentário deletado com sucesso"
        '404':
          description: Comentário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Comentário não encontrado"
        '500':
          description: Erro ao deletar comentário
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro ao deletar comentário"
                  error:
                    type: string
                    example: "Erro interno do servidor"