openapi: 3.0.0
info:
  title: Users
  version: 1.0.0
  description: Users enpoints

paths:
  /api/user:
    get:
      summary: Lista todos os usuários
      tags:
        - Users
      responses:
        200:
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      summary: Cria um novo usuário
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /api/user/{id}:
    get:
      summary: Retorna um usuário específico
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário
      responses:
        200:
          description: Usuário encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      summary: Atualiza um usuário existente (incluindo avatar e headerImage)
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário a ser atualizado
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
                location:
                  type: string
                avatar:
                  type: string
                  format: binary
                headerImage:
                  type: string
                  format: binary
      responses:
        200:
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      summary: Deleta um usuário
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do usuário a ser deletado
      responses:
        200:
          description: Usuário deletado com sucesso

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        username:
          type: string
        bio:
          type: string
        avatar:
          type: string
        headerImage:
          type: string
        password:
          type: string
