swagger: '2.0'
info:
  title: Comment API
  description: API para gerenciamento de comentários
  version: 1.0.0
tags:
  - name: Comment
    description: Operações relacionadas a comentários
paths:
  /api/comment/post/{Id}:
    get:
      tags:
        - Comment
      summary: Retorna todos os comentários de um post específico
      description: Retorna uma lista de comentários associados a um post pelo ID do post.
      parameters:
        - name: Id
          in: path
          description: ID do post
          required: true
          type: string
      responses:
        '200':
          description: Lista de comentários retornada com sucesso
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        '404':
          description: Post não encontrado
        '500':
          description: Erro interno do servidor
  /api/comment/:
    post:
      tags:
        - Comment
      summary: Cria um novo comentário
      description: Cria um novo comentário com os dados fornecidos.
      parameters:
        - name: comment
          in: body
          description: Objeto do comentário
          required: true
          schema:
            $ref: '#/definitions/Comment'
      responses:
        '201':
          description: Comentário criado com sucesso
        '400':
          description: Dados inválidos fornecidos
        '500':
          description: Erro interno do servidor
  /api/comment/{id}:
    delete:
      tags:
        - Comment
      summary: Deleta um comentário
      description: Deleta um comentário pelo ID.
      parameters:
        - name: id
          in: path
          description: ID do comentário
          required: true
          type: string
      responses:
        '200':
          description: Comentário deletado com sucesso
        '404':
          description: Comentário não encontrado
        '500':
          description: Erro interno do servidor
definitions:
  Comment:
    type: object
    properties:
      id:
        type: string
        description: ID do comentário
      postId:
        type: string
        description: ID do post associado ao comentário
      userId:
        type: string
        description: ID do usuário que fez o comentário
      content:
        type: string
        description: Conteúdo do comentário
      createdAt:
        type: string
        format: date-time
        description: Data de criação do comentário
    required:
      - postId
      - userId
      - content